using System.Numerics;
using Raylib_cs;
using static Raylib_cs.Raylib;
namespace MonsterEnergyFlappyBird;
internal static class Program
{
    const int ScreenWidth=1000,ScreenHeight=700; const float GroundY=642f,PlayerX=225f,PlayerW=67f,PlayerH=105f,Gravity=1500f,FlapVelocity=-515f,PipeWidth=112f,PipeGap=220f,PipeSpeed=245f,PipeSpacing=365f;
    sealed class PipePair { public float X,GapCenter; public bool Scored; }
    [STAThread] public static void Main(){SetConfigFlags(ConfigFlags.VSyncHint|ConfigFlags.Msaa4xHint);InitWindow(ScreenWidth,ScreenHeight,"Monster Energy Flappy Bird");SetTargetFPS(144);string a=Path.Combine(AppContext.BaseDirectory,"assets");Texture2D bg=LoadAssetTexture(a,"background"),can=LoadAssetTexture(a,"can"),pipe=LoadAssetTexture(a,"pipe"),over=LoadAssetTexture(a,"gameover");Image icon=LoadAssetImage(a,"can");SetWindowIcon(icon);UnloadImage(icon);var rng=new Random();var pipes=new List<PipePair>(4);ResetPipes(pipes,rng);float y=265,v=0;int score=0,best=0;bool started=false,dead=false;
    while(!WindowShouldClose()){float dt=Math.Clamp(GetFrameTime(),0f,1f/30f);bool flap=IsKeyPressed(KeyboardKey.Space)||IsKeyPressed(KeyboardKey.Up)||IsKeyPressed(KeyboardKey.W)||IsMouseButtonPressed(MouseButton.Left);if(!dead){if(flap){started=true;v=FlapVelocity;}if(started){v+=Gravity*dt;y+=v*dt;foreach(var p in pipes){p.X-=PipeSpeed*dt;if(!p.Scored&&p.X+PipeWidth<PlayerX){p.Scored=true;score++;best=Math.Max(best,score);}}var left=pipes.OrderBy(p=>p.X).First();if(left.X+PipeWidth<-10){left.X=pipes.Max(p=>p.X)+PipeSpacing;left.GapCenter=NextGapCenter(rng);left.Scored=false;}var pr=PlayerCollisionRect(y);if(y<-45||y+PlayerH>GroundY)dead=true;else foreach(var p in pipes){float gt=p.GapCenter-PipeGap/2,gb=p.GapCenter+PipeGap/2;if(CheckCollisionRecs(pr,new Rectangle(p.X,0,PipeWidth,gt))||CheckCollisionRecs(pr,new Rectangle(p.X,gb,PipeWidth,GroundY-gb))){dead=true;break;}}}}else if(flap||IsKeyPressed(KeyboardKey.Enter)){y=265;v=0;score=0;started=false;dead=false;ResetPipes(pipes,rng);}BeginDrawing();ClearBackground(Color.Black);if(!dead){DrawFullscreen(bg);foreach(var p in pipes)DrawPipePair(pipe,p);DrawCan(can,y,v);DrawTextWithShadow(score.ToString(),ScreenWidth/2-MeasureText(score.ToString(),48)/2,32,48,Color.White);if(!started){DrawCenteredPanel("MONSTER FLAPPY",270,44);DrawCenteredPanel("SPACE / CLICK TO FLAP",330,24);}}else{DrawFullscreen(over);string s=$"SCORE  {score}",b=$"BEST   {best}";DrawTextWithShadow(s,ScreenWidth/2-MeasureText(s,42)/2,350,42,new Color(167,255,28,255));DrawTextWithShadow(b,ScreenWidth/2-MeasureText(b,26)/2,405,26,Color.White);}EndDrawing();}UnloadTexture(bg);UnloadTexture(can);UnloadTexture(pipe);UnloadTexture(over);CloseWindow();}
    static string AssetPath(string dir,string name){string png=Path.Combine(dir,name+".png");if(File.Exists(png))return png;string svg=Path.Combine(dir,name+".svg");if(File.Exists(svg))return svg;throw new FileNotFoundException($"Missing asset '{name}'. Tried {png} and {svg}.");}
    static Texture2D LoadAssetTexture(string dir,string name)=>LoadTexture(AssetPath(dir,name));
    static Image LoadAssetImage(string dir,string name)=>LoadImage(AssetPath(dir,name));
    static Rectangle PlayerCollisionRect(float y)=>new(PlayerX+11,y+8,PlayerW-22,PlayerH-16);static void ResetPipes(List<PipePair> p,Random r){p.Clear();for(int i=0;i<4;i++)p.Add(new PipePair{X=720+i*PipeSpacing,GapCenter=NextGapCenter(r)});}static float NextGapCenter(Random r)=>r.Next(210,485);static void DrawFullscreen(Texture2D t)=>DrawTexturePro(t,new Rectangle(0,0,t.Width,t.Height),new Rectangle(0,0,ScreenWidth,ScreenHeight),Vector2.Zero,0,Color.White);static void DrawCan(Texture2D t,float y,float v)=>DrawTexturePro(t,new Rectangle(0,0,t.Width,t.Height),new Rectangle(PlayerX+PlayerW/2,y+PlayerH/2,PlayerW,PlayerH),new Vector2(PlayerW/2,PlayerH/2),Math.Clamp(v/28,-16,32),Color.White);static void DrawPipePair(Texture2D t,PipePair p){float gt=p.GapCenter-PipeGap/2,gb=p.GapCenter+PipeGap/2;DrawTexturePro(t,new Rectangle(0,t.Height,t.Width,-t.Height),new Rectangle(p.X,0,PipeWidth,gt),Vector2.Zero,0,Color.White);DrawTexturePro(t,new Rectangle(0,0,t.Width,t.Height),new Rectangle(p.X,gb,PipeWidth,GroundY-gb),Vector2.Zero,0,Color.White);}static void DrawCenteredPanel(string s,int y,int z){int w=MeasureText(s,z),x=ScreenWidth/2-w/2;DrawRectangleRounded(new Rectangle(x-18,y-8,w+36,z+18),.35f,12,new Color(0,0,0,180));DrawTextWithShadow(s,x,y,z,new Color(171,255,20,255));}static void DrawTextWithShadow(string s,int x,int y,int z,Color c){DrawText(s,x+3,y+3,z,new Color(0,0,0,190));DrawText(s,x,y,z,c);}
}
